### PR TITLE
Remove `withRouter`

### PR DESCRIPTION
**Pull request by josephsavona**
What is `withRouter`? In general it's helpful to introduce as few new concepts at a time. I already know how Relay works, and I was immediately confused by `withRouter`, so I imagine people reading will be too.

### CODE REVIEW

**Comment by schickling** [comment]
I agree! @brene / @lvarayut is this needed here?

**Comment by lvarayut** [comment]
Totally agree with Joseph. I don't think we need it.

**Comment by schickling** [comment]
@lvarayut we just need to make sure it's aligned with the working example project.

**Comment by marktani** [comment]
I remember @brene having a distinct reason for including `withRouter`. In any case I agree that at the moment having it here just introduces a lot of confusion. I think we can add a sentence or two on `withRouter` at this step, and explain it further down the road in the Router chapter. 

Would love to hear @brene's opinion on that :)

**Comment by brene** [comment]
I'm a bit overworked today. I'll look over it tomorrow ;-)

**Comment by brene** [comment]
@josephsavona seems to be right. It looks like some "old" legacy code and we should remove it from all the examples. Previously we used `this.props.router.push('...')`. But I've replaced everything with `Link`. That's the issue. @marktani do you have time to change it in the pokedex example?

**Comment by marktani** [comment]
Ok will do that :+1:

**Comment by alexedev** [comment]
`withRouter` is still used starting from these examples https://learnrelay.org/queries/working-with-fragments

**Comment by marktani** [comment]
Thanks for pointing this out, fixed it in https://github.com/learnrelay/learnrelay/commit/294f4d1b0398ed95269b095b6465aa37e25fe840.

**Pull request merged**
